# Generated by Django 6.0.6 on 2026-08-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied')], default='new', max_length=10),
        ),
    ]
