# Generated by Django 6.0.6 on 2026-08-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_contact_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Image Title')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('sainik', 'Sainik School Jhansi'), ('navodaya', 'Navodaya Vidyalaya'), ('glimpses', 'Other Glimpses')], default='glimpses', max_length=20, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on Gallery')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
